# Generated by Django 2.2.13 on 2024-02-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='External_Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eg_name', models.CharField(max_length=200)),
                ('eg_posts', models.CharField(max_length=200)),
                ('eg_company_name', models.CharField(max_length=50)),
                ('eg_place', models.CharField(max_length=50)),
                ('eg_post_office', models.CharField(max_length=50)),
                ('eg_pin', models.CharField(max_length=50)),
                ('eg_email', models.CharField(max_length=50)),
                ('eg_phone', models.BigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_number', models.CharField(max_length=200)),
                ('grp_leader', models.CharField(default='No name', max_length=50)),
                ('grp_email', models.CharField(max_length=50)),
                ('grp_topic_name', models.CharField(max_length=100)),
                ('GRP_BATCHID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Batch')),
                ('GRP_EG', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.External_Guide')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=200)),
                ('std_regno', models.CharField(max_length=200)),
                ('std_email', models.CharField(max_length=50)),
                ('std_phone', models.BigIntegerField(default=1)),
                ('type_mem_lead', models.CharField(default=1, max_length=200)),
                ('std_batch_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Batch')),
                ('std_group_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Project_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
                ('date', models.CharField(default=1, max_length=100)),
                ('time', models.CharField(max_length=15)),
                ('BATCH', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_file', models.CharField(max_length=100)),
                ('date_upload', models.DateField(max_length=100)),
                ('remark', models.CharField(max_length=500)),
                ('GRP', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Internal_Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_name', models.CharField(max_length=200)),
                ('ig_email', models.CharField(max_length=200)),
                ('ig_phone', models.BigIntegerField(default=1)),
                ('IG', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Group_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRP_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Group')),
                ('LEADER_STUD_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Student')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='GRP_IG',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Internal_Guide'),
        ),
        migrations.AddField(
            model_name='group',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Login'),
        ),
        migrations.AddField(
            model_name='external_guide',
            name='EG',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Login'),
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Circular_date', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('GROUP', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('send_type', models.CharField(max_length=100)),
                ('EXTERNAL', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.External_Guide')),
                ('INTERNAL', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Internal_Guide')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100)),
                ('date_upload', models.CharField(max_length=100)),
                ('GRP_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Group')),
                ('STD_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Student')),
            ],
        ),
    ]
