# Generated by Django 2.2.13 on 2024-02-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completemp', '0002_auto_20240212_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='std_group',
            new_name='std_group_id',
        ),
    ]
