# Generated by Django 2.2.13 on 2024-02-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completemp', '0003_auto_20240212_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='std_group_id',
        ),
    ]
