# Generated by Django 2.2.13 on 2024-02-12 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('completemp', '0004_remove_student_std_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grp_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='completemp.Student'),
        ),
    ]
