# Generated by Django 2.2.13 on 2024-02-17 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('completemp', '0005_auto_20240212_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Punctuality', models.CharField(max_length=100)),
                ('Relevance', models.CharField(max_length=100)),
                ('Presentation_1', models.CharField(max_length=100)),
                ('Presentation_2', models.CharField(max_length=100)),
                ('Presentation_3', models.CharField(max_length=100)),
                ('Demo_report', models.CharField(max_length=100)),
                ('Institution_copy', models.CharField(max_length=100)),
                ('Viva', models.CharField(max_length=100)),
                ('Total', models.CharField(max_length=100)),
                ('GRP', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemp.Group')),
            ],
        ),
    ]
